name: "build_image"

on:
  push:
    paths:
      - "**"
      - "!README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        id: prep
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
              if [[ "${GITHUB_REF}" == refs/heads/*/* ]] ; then
                  git_branch="${GITHUB_REPOSITORY/docker-/}:$(echo $GITHUB_REF | sed "s|refs/heads/||g" | sed "s|/|-|g")"
              else
                  git_branch=${GITHUB_REF#refs/heads/}
              fi

              case "${git_branch}" in
                  "main" | "master" )
                      branch_tag="${GITHUB_REPOSITORY}:latest"
                  ;;
                  "develop" )
                      branch_tag="${GITHUB_REPOSITORY}:develop"
                  ;;
                  * )
                      if [ -n "${{ vars.LATEST }}" ]; then
                          if [ "${{ vars.LATEST }}" = "${branch_tag}" ] || [ "${{ vars.LATEST }}" = "TRUE" ] ; then
                              branch_tag="${GITHUB_REPOSITORY}:${git_branch},${GITHUB_REPOSITORY}:${git_branch}-latest,${GITHUB_REPOSITORY}:latest"
                          else
                              branch_tag="${GITHUB_REPOSITORY}:${git_branch},${GITHUB_REPOSITORY}:${git_branch}-latest"
                          fi
                      else
                          branch_tag="${GITHUB_REPOSITORY}:${git_branch},${GITHUB_REPOSITORY}:${git_branch}-latest"
                      fi
                  ;;
              esac
          fi

          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
              git_tag="${GITHUB_REPOSITORY}:$(echo ${GITHUB_REF} | sed 's|refs/tags/||g')"
          fi

          if [ -n "${branch_tag}" ] && [ -n "${git_tag}" ]; then
              image_tags=${branch_tag},${git_tag}
          else
              image_tags="${branch_tag}${git_tag}"
          fi

          echo "dockerhub_repo=${GITHUB_REPOSITORY/docker-/}" >> $GITHUB_ENV
          dockerhub_images=$(echo "${image_tags}" | sed "s|${GITHUB_REPOSITORY}|docker.io/${GITHUB_REPOSITORY/docker-/}|g")
          ghcr_images=$(echo "${image_tags}" | sed "s|${GITHUB_REPOSITORY}|ghcr.io/${GITHUB_REPOSITORY}|g")
          echo "container_images=${dockerhub_images},${ghcr_images}" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm,arm64

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.container_images }}